# Generated by Django 3.0.8 on 2020-07-24 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_auto_20200724_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='Featured_Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Menu.Featured_Product'),
        ),
    ]
