# Generated by Django 3.0.8 on 2020-07-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_orderitem_featured_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='value',
        ),
    ]
