# Generated by Django 3.0.8 on 2020-07-28 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0010_auto_20200729_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='title',
        ),
    ]
