# Generated by Django 3.0.8 on 2020-07-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0011_remove_account_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Featured_Product',
            new_name='Related_Product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='Featured_Product',
        ),
    ]
