# Generated by Django 3.0.8 on 2020-08-03 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0012_auto_20200729_2334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
