# Generated by Django 3.0.8 on 2020-08-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0014_auto_20200803_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='value',
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
