# Generated by Django 3.0.8 on 2020-08-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0019_shippingaddress_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
