# Generated by Django 3.0.8 on 2020-08-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0020_delete_shippingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Related_Product',
        ),
    ]
