# Generated by Django 3.0.8 on 2020-08-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0022_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
